IMMEDIATE_NOTIFICATION_SCORE = 10 #that's basically just notify score sry for confusion

WATCH_SESSION_SCORE = 5

SESSION_TIMEOUT_MINUTES = 30

SESSION_NEW_NOTIFICATION_STEP = 10

SESSION_MAX_SCORE = 50